import { Post } from '@/@types/post';

export const myPosts: Post[] = [
	{
		id: 1,
		post_type: false,
		user_id: 'user1',
		created_at: '2024-01-10T12:00:00Z',
		title: '리액트 개발 팁 공유',
		content: '리액트 개발에 유용한 팁을 공유합니다.',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 2,
		post_type: false,
		user_id: 'user1',
		created_at: '2024-01-08T09:00:00Z',
		title: 'TypeScript 마이그레이션 경험담',
		content: 'TS로 마이그레이션한 경험을 공유합니다.',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 3,
		post_type: false,
		user_id: 'user1',
		created_at: '2024-01-05T15:00:00Z',
		title: 'UI/UX 디자인 트렌드 2024',
		content: '최신 UI/UX 트렌드를 소개합니다.',
		trade_log_id: null,
		is_public: true,
	},
	// ... (Add the new posts from the user prompt, up to at least 15 for pagination)
	{
		id: 4,
		post_type: false,
		user_id: 'user2',
		created_at: '2024-01-12T10:00:00Z',
		title: '삼성전자의 반도체 부문 실적 전망',
		content:
			'삼성전자가 반도체 사업 부문에서 실적 개선을 위한 계획을 발표했습니다. 다만 글로벌 수급 문제와 경쟁사들과의 격차가 큰 상황에서 어떻게 대응할지, 여러분은 어떻게 예상하시나요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 5,
		post_type: false,
		user_id: 'user3',
		created_at: '2024-01-13T11:00:00Z',
		title: '현대차, 전기차 시장 점유율 확대 전략',
		content:
			'현대차가 전기차 시장에 대한 공격적인 투자를 발표했습니다. 특히, 신규 전기차 모델 출시와 함께 글로벌 시장 점유율 확대를 목표로 하고 있는데, 이에 따른 주가 영향을 어떻게 예측하시나요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 6,
		post_type: false,
		user_id: 'user4',
		created_at: '2024-01-14T12:00:00Z',
		title: '카카오톡, 광고 수익 증가 기대',
		content:
			'카카오는 광고 수익을 통해 실적 개선을 꾀하고 있습니다. 카카오톡 내 광고 서비스가 확장되며, 향후 이 영향이 주가에 미칠 가능성에 대해 여러분은 어떻게 생각하시나요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 7,
		post_type: false,
		user_id: 'user5',
		created_at: '2024-01-15T13:00:00Z',
		title: 'SK텔레콤, 5G 서비스 확장',
		content:
			'SK텔레콤은 5G 서비스 확대에 대한 투자를 계속해서 늘려가고 있습니다. 5G 가입자 증가가 주가에 미칠 영향을 다루어 보았을 때, 긍정적인 전망이 우세할까요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 8,
		post_type: false,
		user_id: 'user6',
		created_at: '2024-01-16T14:00:00Z',
		title: 'LG전자, 가전사업 실적 향상?',
		content:
			'LG전자가 가전 부문에서 실적 향상을 목표로 다양한 신제품을 출시했습니다. 전반적인 소비자 시장 침체에도 불구하고, 가전 시장에서 LG전자가 성공할 수 있을까요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 9,
		post_type: false,
		user_id: 'user7',
		created_at: '2024-01-17T15:00:00Z',
		title: '셀트리온, 바이오 제약 부문 성장 가능성',
		content:
			'셀트리온은 바이오 제약 부문에서 높은 성장 가능성을 보여주고 있습니다. 특히, 항체 의약품의 판매 확대가 주가에 미칠 영향은 긍정적일까요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 10,
		post_type: false,
		user_id: 'user8',
		created_at: '2024-01-18T16:00:00Z',
		title: '네이버, 해외 투자 확대 계획 발표',
		content:
			'네이버가 해외 시장으로의 투자 확대를 발표했습니다. 그에 따른 장기적인 성장 가능성에 대해 여러분의 의견을 듣고 싶습니다.',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 11,
		post_type: false,
		user_id: 'user9',
		created_at: '2024-01-19T17:00:00Z',
		title: 'LG화학, 전기차 배터리 시장 점유율 확대',
		content:
			'LG화학이 전기차 배터리 시장에서 점유율 확대를 위해 추가 투자를 진행 중입니다. 이에 대한 장기적 전망과 주가 반응을 어떻게 보고 계신가요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 12,
		post_type: false,
		user_id: 'user10',
		created_at: '2024-01-20T18:00:00Z',
		title: '삼성바이오로직스, 글로벌 제약사와 협력 강화',
		content:
			'삼성바이오로직스가 글로벌 제약사들과의 협력을 강화하며 성장 가능성을 확대하고 있습니다. 이로 인한 향후 주가 영향을 어떻게 예측하시나요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 13,
		post_type: false,
		user_id: 'user11',
		created_at: '2024-01-21T19:00:00Z',
		title: '현대모비스, 자율주행 기술 혁신',
		content:
			'현대모비스가 자율주행 기술을 혁신적으로 발전시키겠다고 발표했습니다. 자율주행차 시장이 커져가면서 현대모비스 주가에 미칠 영향에 대해 어떤 예상을 하고 계신가요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 14,
		post_type: false,
		user_id: 'user12',
		created_at: '2024-01-22T20:00:00Z',
		title: '카카오게임즈, 신작 게임 흥행 기대',
		content:
			'카카오게임즈가 신작 게임을 출시 예정입니다. 게임의 흥행 여부가 카카오게임즈의 주가에 미칠 영향은 어떻게 될까요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 15,
		post_type: false,
		user_id: 'user13',
		created_at: '2024-01-23T21:00:00Z',
		title: 'POSCO, 수소 경제에 대한 투자 확대',
		content:
			'POSCO가 수소 경제 활성화를 위한 투자를 발표했습니다. 수소 관련 기술이 주가에 미칠 영향에 대해 여러분은 어떻게 생각하시나요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 16,
		post_type: false,
		user_id: 'user14',
		created_at: '2024-01-24T22:00:00Z',
		title: '한화에어로스페이스, 방위산업 투자 확대',
		content:
			'한화에어로스페이스가 방위산업 투자 확대를 위해 신규 계약을 체결했다고 발표했습니다. 이에 대한 주가 영향을 어떻게 분석하시나요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 17,
		post_type: false,
		user_id: 'user15',
		created_at: '2024-01-25T23:00:00Z',
		title: '삼성SDI, 전기차 배터리 기술 혁신',
		content:
			'삼성SDI가 전기차 배터리 기술 혁신을 위해 R&D 투자를 늘리고 있습니다. 전기차 배터리 시장에서 삼성SDI의 경쟁력을 어떻게 평가하시나요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 18,
		post_type: false,
		user_id: 'user16',
		created_at: '2024-01-26T08:00:00Z',
		title: '두산중공업, 해외 프로젝트 수주 확대',
		content:
			'두산중공업이 해외 프로젝트 수주를 확대하고 있습니다. 이에 따라 주가 상승 전망이 있을까요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 19,
		post_type: false,
		user_id: 'user17',
		created_at: '2024-01-27T09:00:00Z',
		title: 'SK이노베이션, 리튬 배터리 사업 성장 전망',
		content:
			'SK이노베이션이 리튬 배터리 시장에 적극적인 투자를 진행하고 있습니다. 리튬 배터리 사업의 성장 가능성에 대한 여러분의 의견을 듣고 싶습니다.',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 20,
		post_type: false,
		user_id: 'user18',
		created_at: '2024-01-28T10:00:00Z',
		title: '아모레퍼시픽, 글로벌 뷰티 시장 진출',
		content:
			'아모레퍼시픽이 글로벌 뷰티 시장에 적극적으로 진출하고 있습니다. 이를 통해 매출 증가와 주가 상승을 기대할 수 있을까요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 21,
		post_type: false,
		user_id: 'user19',
		created_at: '2024-01-29T11:00:00Z',
		title: '삼성전기, 부품 사업 성장 가능성',
		content:
			'삼성전기가 부품 사업의 성장을 목표로 추가 투자 계획을 발표했습니다. 특히, 전자 부품 사업에서의 경쟁력을 높일 수 있을까요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 22,
		post_type: false,
		user_id: 'user20',
		created_at: '2024-01-30T12:00:00Z',
		title: '현대글로비스, 물류 시장 경쟁력 강화',
		content:
			'현대글로비스가 물류 시장 경쟁력을 강화하기 위해 기술 혁신에 투자하고 있습니다. 이에 따른 향후 주가 전망은 어떻게 보시나요?',
		trade_log_id: null,
		is_public: true,
	},
	{
		id: 23,
		post_type: false,
		user_id: 'user21',
		created_at: '2024-01-31T13:00:00Z',
		title: '대한항공, 국제선 운항 재개 계획',
		content:
			'대한항공이 국제선 운항을 재개할 계획을 발표했습니다. 국제선 수요 증가가 주가에 미칠 긍정적인 영향에 대해 어떻게 보시나요?',
		trade_log_id: null,
		is_public: true,
	},
];
